spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/AutoPOS
    username: postgres
    password: test12

  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true

liquibase:
  change-log: classpath:/liquibase/master.xml

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
